def brooke4():
    i01.head.rothead.attach()
    i01.head.neck.attach()
    lookrightside()
    sleep(4)
    lookleftside()
    sleep(4)
    lookinmiddle()
    sleep(4)
    lookrightside()
    sleep(4)
    lookleftside()
    sleep(4)
    lookinmiddle()
    sleep(4)
    i01.detach()
    sleep(20)
    brooke2()     