def brooke4():
  i01.head.rothead.enable()
  i01.head.neck.enable()
  lookrightside()
  sleep(4)
  lookleftside()
  sleep(4)
  lookinmiddle()
  sleep(4)
  lookrightside()
  sleep(4)
  lookleftside()
  sleep(4)
  lookinmiddle()
  sleep(4)
  i01.disable()
  sleep(20)
  brooke2()   
