def bookcat():
  i01.mouth.speakBlocking("Cat the cat, who is that?")
  sleep(2)
  chatBot.getResponse("SAY " + "lets turn the page")
  sleep(1)
  i01.mouth.speakBlocking("It's mouse, the mouse! Hi, mouse the mouse!  Hello there")
  sleep(2)
  chatBot.getResponse("SAY " + "lets turn the page")
  sleep(1)
  i01.mouth.speakBlocking("Cat the cat, who is that?")
  sleep(2)
  chatBot.getResponse("SAY " + "lets turn the page")
  sleep(1)
  i01.mouth.speakBlocking("It's duck the duck! Hi, duck the duck! A pleasure, as always")
  sleep(2)
  chatBot.getResponse("SAY " + "lets turn the page")
  sleep(1)
  i01.mouth.speakBlocking("Cat the cat, who is that?")
  sleep(2)
  chatBot.getResponse("SAY " + "lets turn the page")
  sleep(1)
  i01.mouth.speakBlocking("It's fish the fish! Hi, fish the fish! Hey dude")
  sleep(2)
  chatBot.getResponse("SAY " + "lets turn the page")
  sleep(1)
  i01.mouth.speakBlocking("Cat the cat likes her friends. Sure do")
  sleep(2)
  chatBot.getResponse("SAY " + "lets turn the page")
  sleep(1)
  i01.mouth.speakBlocking("Cat the cat, who is that?  eep")
  sleep(2)
  chatBot.getResponse("SAY " + "lets turn the page")
  sleep(1)
  i01.mouth.speakBlocking("I have no idea.  blarggie! blarggie")
  sleep(2)
  chatBot.getResponse("SAY " + "lets turn the page")
  sleep(1)
  i01.mouth.speakBlocking("Maybe")
  sleep(2)
  chatBot.getResponse("SAY " + "lets turn the page")
  sleep(1)
  i01.mouth.speakBlocking("Blarggie! Blarggie!  It's a new friend! Blarggie! Blarggie")
  sleep(2)
  chatBot.getResponse("SAY " + "lets turn the page")
  sleep(1)
  i01.mouth.speakBlocking("The end")


def bookcatYes():
  print "book cat yes"
  i01.moveHead(20,90,30)

def bookcatNo():
  print "book cat no"
  i01.moveHead(120,90,30)
