
def playsong(data):
  inMoov.startedGesture()
  if (data == "can i have your attention"): # Могу ли я привлечь ваше внимание
    inMoov.mouth.speak("ok you have my attention")
    #inMoov.mouth.speak(u"Хорошо, что я привлёк ваше внимание")
    stopit()
    inMoov.mouth.speak("electro funk inmoov")
    #inMoov.mouth.speak(u"Электо функции Инмоова")
    inMoov.setHeadVelocity(-1,-1)
    inMoov.setArmVelocity("left",-1.0,-1.0,-1.0,-1.0)
    inMoov.setArmVelocity("right",-1.0,-1.0,-1.0,-1.0)
    inMoov.setHandVelocity("left",-1,-1,-1,-1,-1,-1)
    inMoov.setHandVelocity("right",-1,-1,-1,-1,-1,-1)
    inMoov.setTorsoVelocity(-1.0,-1.0,-1.0)
    #for x in range(5):
    inMoov.moveHead(60,90)
    sleep(2)
    inMoov.moveHead(110,80)
    sleep(2)
    inMoov.moveHead(60,90)
    sleep(2)
    inMoov.moveHead(110,80)
    sleep(2)
    inMoov.moveHead(60,90)
    sleep(2)
    inMoov.moveHead(110,80)
    sleep(2)
    inMoov.moveHead(60,90)
    sleep(2)
    inMoov.moveHead(110,80)
    sleep(2)
    inMoov.moveHead(60,90)
    sleep(2)
    inMoov.moveHead(110,80)
    sleep(2)
    inMoov.moveHead(60,90)
    sleep(2)
    inMoov.moveHead(110,80)
    sleep(2)
    inMoov.moveHead(60,90)
    fingerright()
    sleep(3)
    inMoov.moveHead(110,80)
    fingerleft()
    sleep(3)
    inMoov.moveHead(60,90)
    fingerright()
    sleep(3)
    inMoov.moveHead(110,80)
    fingerleft()
    sleep(3)
    inMoov.moveHead(60,90)
    fingerright()
    sleep(3)
    inMoov.moveHead(110,80)
    fingerleft()
    sleep(3)
    inMoov.moveHead(60,90)
    fingerright()
    sleep(3)
    inMoov.moveHead(110,80)
    fingerleft()
    sleep(3)
    inMoov.moveTorso(90,90,90)
    fullspeed()
    inMoov.giving()
    sleep(5)
    inMoov.armsFront()
    sleep(4)
    fullspeed()
    inMoov.daVinci()
    sleep(5)
    surrender()
    sleep(6)
    inMoov.giving()
    sleep(6)
    inMoov.moveHead(60,90)
    fingerright()
    sleep(3)
    inMoov.moveHead(110,80)
    fingerleft()
    sleep(3)
    inMoov.moveHead(60,90)
    fingerright()
    sleep(3)
    inMoov.moveHead(110,80)
    fingerleft()
    relax()
    inMoov.moveTorso(90,90,90)
    sleep(3)
    fullspeed()
    sleep(3)
    madeby()
    relax()
    sleep(5)
    inMoov.disable()
  inMoov.finishedGesture()

  
   


