def trackPoint():
  if (inMoov.RobotIsOpenCvCapturing()):
    inMoov.opencv.removeFilter("Gray")
    inMoov.opencv.removeFilter("PyramidDown")
    inMoov.opencv.removeFilter("FaceRecognizer")
  inMoov.startHeadTracking("leftPort",12,13)
  #inMoov.startEyesTracking("leftPort",22,24)
  #inMoov.eyesTracking.pid.setPID("x",eyeXPidKp,eyeXPidKi,eyeXPidKd)
  #inMoov.eyesTracking.pid.setPID("y",eyeYPidKp,eyeYPidKi,eyeYPidKd)
  inMoov.headTracking.pid.setPID("x",rotheadPidKp,rotheadPidKi,rotheadPidKd)
  inMoov.headTracking.pid.setPID("y",neckPidKp,neckPidKi,neckPidKd)
  sleep(1)
  inMoov.headTracking.startLKTracking()
  #inMoov.eyesTracking.startLKTracking()
  inMoov.setHeadVelocity(80, -1)
  inMoov.head.rollNeck.setOverrideAutoDisable(True)
  inMoov.head.rollNeck.moveToBlocking(90)
  sleep(1)
  fullspeed()
