def trackHumans():
  if (i01.RobotIsOpenCvCapturing()):
    i01.opencv.removeFilter("Gray")
    i01.opencv.removeFilter("PyramidDown")
    i01.opencv.removeFilter("FaceRecognizer")
  i01.startHeadTracking("leftPort",12,13)
  #i01.startEyesTracking("leftPort",22,24)
  #i01.eyesTracking.pid.setPID("eyeX",eyeXPidKp,eyeXPidKi,eyeXPidKd)
  #i01.eyesTracking.pid.setPID("eyeY",eyeYPidKp,eyeYPidKi,eyeYPidKd)
  i01.headTracking.pid.setPID("x",rotheadPidKp,rotheadPidKi,rotheadPidKd)
  i01.headTracking.pid.setPID("y",neckPidKp,neckPidKi,neckPidKd)
  sleep(1)
  i01.headTracking.faceDetect()
  #i01.eyesTracking.faceDetect()
  i01.setHeadVelocity(80, -1)
  i01.moveHead.rollNeck(90)
  sleep(1)
  fullspeed()
