def brooke4():
  inMoov.head.rothead.enable()
  inMoov.head.neck.enable()
  lookrightside()
  sleep(4)
  lookleftside()
  sleep(4)
  lookinmiddle()
  sleep(4)
  lookrightside()
  sleep(4)
  lookleftside()
  sleep(4)
  lookinmiddle()
  sleep(4)
  inMoov.disable()
  sleep(20)
  brooke2()   
